#!/usr/bin/env python

import os
import collections
import argparse
import numpy
import spglib
import math
import ciflib
#-------------------------------------------------------------
if __name__ == '__main__':
    ciflib.main()
